import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Button } from 'react-bootstrap';
import { FormEvent, useRef } from 'react';
const inter = Inter({ subsets: ['latin'] })

export default  function Home() {
  const nameRef=useRef<HTMLInputElement>(null);
  const emailRef=useRef<HTMLInputElement>(null);
  const textRef=useRef<HTMLTextAreaElement>(null);
  const handleSubmit=async(e: FormEvent<HTMLFormElement>)=>{
    let data={
      name:nameRef.current?.value,
      email:emailRef.current?.value,
      message:textRef.current?.value,
    }
    e.preventDefault();
    await fetch("/api/contact",{
      method:"POST",
      headers:{
        Accept: "application/json, text/plain, */*",
        "Content-Type": "application/json",
      },
      body:JSON.stringify(data),
    }).then((res)=>{
      if(res.status===200){
        window.alert("メール送信成功");
      }
    })

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container mt-5'>
        <h2 className='mb-3'>Next.js Gmailアプリ</h2>
        <form onSubmit={(e:FormEvent<HTMLFormElement>)=>handleSubmit(e)}>
          <div className="mb-3">
            <label htmlFor="name" className='form-label'>
              お名前
            </label>
            <input 
              type="text"  
              className='form-control' 
              id='name' 
              required
              ref={nameRef}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="email" className='form-label'>
              メールアドレス
            </label>
            <input type="email"  className='form-control' id='name' required ref={emailRef}/>
          </div>
          <div className="mb-3">
            <label htmlFor="message" className='form-label'>
              メッセージ
            </label>
            <textarea  className='form-control' id='name' required ref={textRef}/>
          </div>
          <button type='submit' className='btn btn-danger'>
            メール送信
          </button>
        </form>
      </div>
    </>
  )
}
